### ISSUE TITLE
ERROR 500 on new nuBuilder Forte installation on WP 5.2.1

### ISSUE THREAD

**Issue by quistuipater** [steven-copley/nubuilder-forte#1]
I’m on WordPress 5.2.1 with PHP version is 7.0.33 (the platform is Bluehost). I just installed the nuBuilder Forte version 1.5 plugin. The WordPress dashboard entry appears but when I click on the ```Start nuBuilder``` button I get:

```"This page isn’t working xxxxxxxx is currently unable to handle this request. HTTP ERROR 500"```

I have an error logged in error_log:

```
[31-May-2019 20:39:21 UTC] PHP Warning:  base64_decode() expects parameter 1 to be string, array given in /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php on line 1559
[31-May-2019 20:39:21 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2019] Unknown character set in /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php:1732
Stack trace:
#0 /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php(1732): PDO->__construct('mysql:host=DB_H...', 'DB_USER', 'DB_PASSWORD', Array)
#1 /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php(717): nubuilderInitDB()
#2 /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php(664): nuSessionInitialization()
#3 /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/index.php(6): nuInitialization()
#4 {main}
  thrown in /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php on line 1732
```

nubuilder-include.php line 1559 is:

```$decode = base64_decode($_SESSION['nubuilder_wordpress_session_data']);```

And nubuilder-include.php line 1732 is:

```$nuDB = new PDO("mysql:host=$DBHost;dbname=$DBName;charset=$DBCharset", $DBUser, $DBPassword, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES $DBCharset"));``

So, after a bit of poking around it appears that $DBCharset is not set.

Help.

**Comment by quistuipater** [comment]
Kinda quiet around here ...

**Comment by iFuzzle** [comment]
Hey, it might be late but hopefully not too late. I just opened issue #2
I am trying to install nubuilder without WP and maybe you could try entering your data directly into nubuilder-include.php as a hotfix.

**Comment by quistuipater** [comment]
I gave up on this software a looooong time ago.

**Comment by iFuzzle** [comment]
Can you suggest an alternativ?
I need to provide low-code and web-based way to create simple apps.

**Comment by steven-copley** [comment]
> I’m on WordPress 5.2.1 with PHP version is 7.0.33 (the platform is Bluehost). I just installed the nuBuilder Forte version 1.5 plugin. The WordPress dashboard entry appears but when I click on the `Start nuBuilder` button I get:
> 
> `"This page isn’t working xxxxxxxx is currently unable to handle this request. HTTP ERROR 500"`
> 
> I have an error logged in error_log:
> 
> ```
> [31-May-2019 20:39:21 UTC] PHP Warning:  base64_decode() expects parameter 1 to be string, array given in /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php on line 1559
> [31-May-2019 20:39:21 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2019] Unknown character set in /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php:1732
> Stack trace:
> #0 /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php(1732): PDO->__construct('mysql:host=DB_H...', 'DB_USER', 'DB_PASSWORD', Array)
> #1 /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php(717): nubuilderInitDB()
> #2 /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php(664): nuSessionInitialization()
> #3 /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/index.php(6): nuInitialization()
> #4 {main}
>   thrown in /home1/yyyyyyyy/public_html/xxxxxxxx/service/wp-content/plugins/nubuilder-forte/nubuilder-include.php on line 1732
> ```
> 
> nubuilder-include.php line 1559 is:
> 
> `$decode = base64_decode($_SESSION['nubuilder_wordpress_session_data']);`
> 
> And nubuilder-include.php line 1732 is:
> 
> ```$nuDB = new PDO("mysql:host=$DBHost;dbname=$DBName;charset=$DBCharset", $DBUser, $DBPassword, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES $DBCharset"));``
> 
> So, after a bit of poking around it appears that $DBCharset is not set.
> 
> Help.

I'm sorry but we are no longer supporting the WordPress version of nuBuilder.
